{-
The sequence of triangle numbers is generated by adding the natural numbers. So
the 7th triangle number would be 1 +2 +3 +4 +5 +6 +7 = 28. The first ten terms
would be: 1,3,6,10,15,21,28,36,45,55,...

Let us list the factors of the first seven triangle numbers:
1:1
3:1,3
6:1,2,3,6
10:1,2,5,10
15:1,3,5,15
21:1,3,7,21
28:1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
-}

memoize :: (Int -> a) -> (Int -> a)
memoize f = (map f [0 ..] !!)

triangle :: (Num a, Enum a) => a -> a
triangle n = sum [1 .. n]

memoTriangle :: Int -> Int
memoTriangle = memoize triangle

factors :: (Integral a) => a -> [a]
factors n = [x | x <- [1 .. n], n `mod` x == 0]

memoFactors :: Int -> [Int]
memoFactors = memoize factors

newFactors :: (Integral a) => a -> [a]
newFactors n = [x | x <- [1 .. floor . sqrt . fromIntegral $ n + 1], n `mod` x == 0]

memoNewFactors :: Int -> [Int]
memoNewFactors = memoize newFactors

main :: IO ()
-- main = print $ triangle $ length $ takeWhile (<= 6) $ map length $ map memoFactors $ map memoTriangle [1 ..]
main = print $ triangle $ length $ takeWhile (<= 6) $ map length $ map memoNewFactors $ map memoTriangle [1 ..]
